# Generated by Django 6.1 on 2026-09-02 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=255)),
                ('missed_count', models.IntegerField(blank=True, null=True)),
                ('period_days', models.IntegerField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.patient')),
            ],
            options={
                'db_table': 'alerts',
                'indexes': [models.Index(fields=['patient'], name='alerts_patient_b5e92e_idx'), models.Index(fields=['is_resolved'], name='alerts_is_reso_d52617_idx')],
            },
        ),
    ]
