# Generated by Django 6.1 on 2026-09-02 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage_description', models.CharField(max_length=150)),
                ('frequency', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='accounts.patient')),
            ],
            options={
                'db_table': 'medications',
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.TimeField()),
                ('days_of_week', models.CharField(default='ALL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medication')),
            ],
            options={
                'db_table': 'medication_schedules',
            },
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['patient'], name='medications_patient_fe125f_idx'),
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['is_active'], name='medications_is_acti_1348f5_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['medication'], name='medication__medicat_a6c949_idx'),
        ),
    ]
