# Generated by Django 6.1 on 2026-09-02 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='scheduled', max_length=10)),
                ('action_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_records', to='medications.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_records', to='accounts.patient')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_records', to='medications.medicationschedule')),
            ],
            options={
                'db_table': 'dose_records',
                'indexes': [models.Index(fields=['patient', 'scheduled_date'], name='dose_record_patient_07bece_idx'), models.Index(fields=['status'], name='dose_record_status_dc695f_idx')],
                'unique_together': {('schedule', 'scheduled_date', 'scheduled_time')},
            },
        ),
    ]
