# Generated by Django 6.1 on 2026-09-02 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdherenceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_scheduled', models.IntegerField(default=0)),
                ('total_taken', models.IntegerField(default=0)),
                ('total_missed', models.IntegerField(default=0)),
                ('adherence_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='low', max_length=10)),
                ('detected_patterns', models.JSONField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence_analyses', to='accounts.patient')),
            ],
            options={
                'db_table': 'adherence_analysis',
                'indexes': [models.Index(fields=['patient', 'period_type', 'period_start'], name='adherence_a_patient_fae689_idx')],
            },
        ),
    ]
